const $=(s)=>document.querySelector(s);
const els={main:$('#mainApp'),login:$('#loginView'),loginForm:$('#loginForm'),adminKey:$('#adminKey'),remember:$('#rememberKey'),loginError:$('#loginError'),logout:$('#logoutBtn'),refresh:$('#refreshBtn'),export:$('#exportBtn'),lastUpdated:$('#lastUpdated'),rows:$('#transactionRows'),cards:$('#transactionCards'),empty:$('#emptyState'),resultCount:$('#resultCount'),search:$('#searchInput'),type:$('#typeFilter'),provider:$('#providerFilter'),status:$('#statusFilter'),from:$('#fromDate'),to:$('#toDate'),clear:$('#clearFilters'),dialog:$('#detailDialog'),detailTitle:$('#detailTitle'),detailBody:$('#detailBody'),closeDialog:$('#closeDialog')};
let adminKey=sessionStorage.getItem('payhub_admin_key')||localStorage.getItem('payhub_admin_key')||'';
let transactions=[];
let filtered=[];
const money=(c,currency='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency}).format((Number(c)||0)/100);
const dt=(value)=>value?new Date(value).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}):'—';
const esc=(v)=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const typeLabel=(t)=>({tip:'Tip',song_request:'Song Request',invoice:'Invoice Payment',vocal_tutorial:'Vocal Tutorial'}[t]||String(t||'Sale').replaceAll('_',' '));
function paymentMethod(tx){return tx.paymentMethod||tx.metadata?.paymentMethod||tx.metadata?.fundingSource||(tx.provider==='square'?'Square':tx.provider==='paypal'?'PayPal':tx.provider||'—');}
function detailText(tx){if(tx.type==='song_request')return tx.metadata?.song||tx.description||'Song request';if(tx.type==='tip')return tx.description||tx.metadata?.note||'Tip';if(tx.type==='invoice')return tx.metadata?.invoiceNumber?`Invoice ${tx.metadata.invoiceNumber}`:(tx.description||tx.reference||'Invoice payment');if(tx.type==='vocal_tutorial')return tx.description||'Diamond Method';return tx.description||tx.title||'';}
async function api(path){const r=await fetch(path,{headers:{authorization:`Bearer ${adminKey}`,'cache-control':'no-store'}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d;}
async function loadAll(){els.refresh.disabled=true;try{let offset=0;const limit=500;const all=[];let total=Infinity;while(offset<total){const d=await api(`/api/admin/transactions?limit=${limit}&offset=${offset}`);const batch=d.transactions||[];all.push(...batch);total=Number.isFinite(Number(d.total))?Number(d.total):all.length;if(!batch.length||batch.length<limit)break;offset+=batch.length;}transactions=all;applyFilters();showApp();els.lastUpdated.textContent=`Updated ${new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})} · ${transactions.length} transactions loaded`;}catch(e){if(/Unauthorized/i.test(e.message)){lock(e.message);}else{els.lastUpdated.textContent=e.message;}}finally{els.refresh.disabled=false;}}
function showApp(){els.login.classList.add('hidden');els.main.classList.remove('hidden');els.logout.classList.remove('hidden');}
function lock(message=''){adminKey='';sessionStorage.removeItem('payhub_admin_key');localStorage.removeItem('payhub_admin_key');els.main.classList.add('hidden');els.logout.classList.add('hidden');els.login.classList.remove('hidden');els.loginError.textContent=message==='Unauthorized.'?'That admin key was not accepted.':message;}
function updateStats(){const paid=transactions.filter(t=>t.status==='PAID');const sum=(arr)=>arr.reduce((s,t)=>s+(Number(t.amountCents)||0),0);const tips=paid.filter(t=>t.type==='tip');const songs=paid.filter(t=>t.type==='song_request');const other=paid.filter(t=>!['tip','song_request'].includes(t.type));$('#statRevenue').textContent=money(sum(paid));$('#statPaidCount').textContent=`${paid.length} paid sale${paid.length===1?'':'s'}`;$('#statTips').textContent=money(sum(tips));$('#statTipCount').textContent=`${tips.length} tip${tips.length===1?'':'s'}`;$('#statSongs').textContent=money(sum(songs));$('#statSongCount').textContent=`${songs.length} request${songs.length===1?'':'s'}`;$('#statOther').textContent=money(sum(other));$('#statOtherCount').textContent=`${other.length} sale${other.length===1?'':'s'}`;}
function applyFilters(){const q=els.search.value.trim().toLowerCase();const from=els.from.value?new Date(`${els.from.value}T00:00:00`):null;const to=els.to.value?new Date(`${els.to.value}T23:59:59.999`):null;filtered=transactions.filter(tx=>{if(els.type.value&&tx.type!==els.type.value)return false;if(els.provider.value&&tx.provider!==els.provider.value)return false;if(els.status.value&&tx.status!==els.status.value)return false;const when=new Date(tx.paidAt||tx.createdAt||0);if(from&&when<from)return false;if(to&&when>to)return false;if(q){const hay=[tx.id,tx.type,tx.title,tx.description,tx.reference,tx.customerName,tx.customerEmail,tx.customerPhone,tx.provider,tx.providerPaymentId,tx.providerOrderId,paymentMethod(tx),JSON.stringify(tx.metadata||{})].join(' ').toLowerCase();if(!hay.includes(q))return false;}return true;});updateStats();render();}
function render(){els.rows.innerHTML='';els.cards.innerHTML='';els.resultCount.textContent=filtered.length;els.empty.classList.toggle('hidden',filtered.length>0);for(const tx of filtered){const tr=document.createElement('tr');tr.className='clickable';tr.innerHTML=`<td>${esc(dt(tx.paidAt||tx.createdAt))}</td><td><strong>${esc(typeLabel(tx.type))}</strong><small>${esc(detailText(tx))}</small></td><td><strong>${esc(tx.customerName||'—')}</strong><small>${esc(tx.customerEmail||tx.customerPhone||'')}</small></td><td class="money">${esc(money(tx.amountCents,tx.currency||'USD'))}</td><td><span class="provider-badge ${esc(tx.provider||'')}">${esc(paymentMethod(tx))}</span></td><td><span class="status ${String(tx.status||'').toLowerCase()}">${esc(tx.status||'—')}</span></td>`;tr.addEventListener('click',()=>openDetail(tx));els.rows.appendChild(tr);const card=document.createElement('article');card.className='tx-card';card.innerHTML=`<div class="tx-top"><div><div class="tx-title">${esc(typeLabel(tx.type))}</div><div class="tx-sub">${esc(detailText(tx))}</div></div><div class="tx-money">${esc(money(tx.amountCents,tx.currency||'USD'))}</div></div><div class="tx-meta"><span>${esc(tx.customerName||'Unknown customer')}</span><span>•</span><span>${esc(paymentMethod(tx))}</span><span>•</span><span>${esc(dt(tx.paidAt||tx.createdAt))}</span></div>`;card.addEventListener('click',()=>openDetail(tx));els.cards.appendChild(card);}}
function item(label,value,wide=false,code=false){return `<div class="detail-item${wide?' wide':''}"><span>${esc(label)}</span>${code?`<code>${esc(value||'—')}</code>`:`<strong>${esc(value||'—')}</strong>`}</div>`;}
function openDetail(tx){els.detailTitle.textContent=`${typeLabel(tx.type)} · ${money(tx.amountCents,tx.currency||'USD')}`;const meta=tx.metadata&&Object.keys(tx.metadata).length?JSON.stringify(tx.metadata,null,2):'No extra metadata';els.detailBody.innerHTML=[item('Status',tx.status),item('Paid with',paymentMethod(tx)),item('Processor',tx.provider||'—'),item('Fulfillment',tx.fulfillmentStatus||'—'),item('Customer',tx.customerName||'—'),item('Email',tx.customerEmail||'—'),item('Phone',tx.customerPhone||'—'),item('What it was for',detailText(tx)),item('Created',dt(tx.createdAt)),item('Paid',dt(tx.paidAt)),item('Intent ID',tx.id,true,true),item('Provider payment ID',tx.providerPaymentId||'—',true,true),item('Provider order ID',tx.providerOrderId||'—',true,true),item('Reference',tx.reference||'—',true,true),`<div class="detail-item wide"><span>Metadata / notes</span><pre class="detail-json">${esc(meta)}</pre></div>`].join('');els.dialog.showModal();}
function exportCsv(){const cols=['paid_at','created_at','type','description','customer_name','customer_email','customer_phone','amount','currency','payment_method','provider','status','fulfillment_status','reference','intent_id','provider_payment_id','provider_order_id','metadata'];const quote=v=>`"${String(v??'').replaceAll('"','""')}"`;const lines=[cols.join(',')];for(const t of filtered){lines.push([t.paidAt,t.createdAt,typeLabel(t.type),detailText(t),t.customerName,t.customerEmail,t.customerPhone,(Number(t.amountCents||0)/100).toFixed(2),t.currency,paymentMethod(t),t.provider,t.status,t.fulfillmentStatus,t.reference,t.id,t.providerPaymentId,t.providerOrderId,JSON.stringify(t.metadata||{})].map(quote).join(','));}const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pay-hub-sales-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
els.loginForm.addEventListener('submit',async e=>{e.preventDefault();adminKey=els.adminKey.value.trim();els.loginError.textContent='';if(els.remember.checked)localStorage.setItem('payhub_admin_key',adminKey);else sessionStorage.setItem('payhub_admin_key',adminKey);await loadAll();});
els.logout.addEventListener('click',()=>lock());els.refresh.addEventListener('click',loadAll);els.export.addEventListener('click',exportCsv);[els.search,els.type,els.provider,els.status,els.from,els.to].forEach(el=>el.addEventListener(el===els.search?'input':'change',applyFilters));els.clear.addEventListener('click',()=>{[els.search,els.type,els.provider,els.status,els.from,els.to].forEach(el=>el.value='');applyFilters();});els.closeDialog.addEventListener('click',()=>els.dialog.close());els.dialog.addEventListener('click',e=>{if(e.target===els.dialog)els.dialog.close();});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
if(adminKey){els.remember.checked=Boolean(localStorage.getItem('payhub_admin_key'));loadAll();}
setInterval(()=>{if(adminKey&&!document.hidden)loadAll();},60000);
