const $=(s)=>document.querySelector(s);
const els={main:$('#mainApp'),login:$('#loginView'),loginForm:$('#loginForm'),adminKey:$('#adminKey'),remember:$('#rememberKey'),loginError:$('#loginError'),logout:$('#logoutBtn'),refresh:$('#refreshBtn'),export:$('#exportBtn'),lastUpdated:$('#lastUpdated'),rows:$('#transactionRows'),cards:$('#transactionCards'),empty:$('#emptyState'),resultCount:$('#resultCount'),search:$('#searchInput'),type:$('#typeFilter'),provider:$('#providerFilter'),status:$('#statusFilter'),from:$('#fromDate'),to:$('#toDate'),clear:$('#clearFilters'),dialog:$('#detailDialog'),detailEyebrow:$('#detailEyebrow'),detailTitle:$('#detailTitle'),detailBody:$('#detailBody'),closeDialog:$('#closeDialog'),listViewBtn:$('#listViewBtn'),calendarViewBtn:$('#calendarViewBtn'),listView:$('#listView'),calendarView:$('#calendarView'),viewHeading:$('#viewHeading'),calendarMonth:$('#calendarMonth'),calendarSummary:$('#calendarSummary'),calendarGrid:$('#calendarGrid'),calendarPrev:$('#calendarPrev'),calendarNext:$('#calendarNext'),calendarToday:$('#calendarToday')};
let adminKey=sessionStorage.getItem('payhub_admin_key')||localStorage.getItem('payhub_admin_key')||'';
let transactions=[];
let filtered=[];
let currentView=localStorage.getItem('payhub_view')==='calendar'?'calendar':'list';
let calendarCursor=new Date();
calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth(),1);
const money=(c,currency='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency}).format((Number(c)||0)/100);
const dt=(value)=>value?new Date(value).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}):'—';
const esc=(v)=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const typeLabel=(t)=>({tip:'Tip',song_request:'Song Request',invoice:'Invoice Payment',vocal_tutorial:'Vocal Tutorial'}[t]||String(t||'Sale').replaceAll('_',' '));
function paymentMethod(tx){return tx.paymentMethod||tx.metadata?.paymentMethod||tx.metadata?.fundingSource||(tx.provider==='square'?'Square':tx.provider==='paypal'?'PayPal':tx.provider||'—');}
function detailText(tx){if(tx.type==='song_request')return tx.metadata?.song||tx.description||'Song request';if(tx.type==='tip')return tx.description||tx.metadata?.note||'Tip';if(tx.type==='invoice')return tx.metadata?.invoiceNumber?`Invoice ${tx.metadata.invoiceNumber}`:(tx.description||tx.reference||'Invoice payment');if(tx.type==='vocal_tutorial')return tx.description||'Diamond Method';return tx.description||tx.title||'';}
function txDate(tx){return new Date(tx.paidAt||tx.createdAt||0);}
function localDateKey(value){const d=value instanceof Date?value:new Date(value);if(Number.isNaN(d.getTime()))return'';const y=d.getFullYear();const m=String(d.getMonth()+1).padStart(2,'0');const day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`;}
async function api(path){const r=await fetch(path,{headers:{authorization:`Bearer ${adminKey}`,'cache-control':'no-store'}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d;}
async function loadAll(){els.refresh.disabled=true;try{let offset=0;const limit=500;const all=[];let total=Infinity;while(offset<total){const d=await api(`/api/admin/transactions?limit=${limit}&offset=${offset}`);const batch=d.transactions||[];all.push(...batch);total=Number.isFinite(Number(d.total))?Number(d.total):all.length;if(!batch.length||batch.length<limit)break;offset+=batch.length;}transactions=all;applyFilters();showApp();els.lastUpdated.textContent=`Updated ${new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})} · ${transactions.length} transactions loaded`;}catch(e){if(/Unauthorized/i.test(e.message)){lock(e.message);}else{els.lastUpdated.textContent=e.message;els.loginError.textContent=e.message;}}finally{els.refresh.disabled=false;}}
function showApp(){els.login.classList.add('hidden');els.main.classList.remove('hidden');els.logout.classList.remove('hidden');setView(currentView);}
function lock(message=''){adminKey='';sessionStorage.removeItem('payhub_admin_key');localStorage.removeItem('payhub_admin_key');els.main.classList.add('hidden');els.logout.classList.add('hidden');els.login.classList.remove('hidden');els.loginError.textContent=message==='Unauthorized.'?'That admin key was not accepted.':message;}
function updateStats(){const paid=transactions.filter(t=>t.status==='PAID');const sum=(arr)=>arr.reduce((s,t)=>s+(Number(t.amountCents)||0),0);const tips=paid.filter(t=>t.type==='tip');const songs=paid.filter(t=>t.type==='song_request');const other=paid.filter(t=>!['tip','song_request'].includes(t.type));$('#statRevenue').textContent=money(sum(paid));$('#statPaidCount').textContent=`${paid.length} paid sale${paid.length===1?'':'s'}`;$('#statTips').textContent=money(sum(tips));$('#statTipCount').textContent=`${tips.length} tip${tips.length===1?'':'s'}`;$('#statSongs').textContent=money(sum(songs));$('#statSongCount').textContent=`${songs.length} request${songs.length===1?'':'s'}`;$('#statOther').textContent=money(sum(other));$('#statOtherCount').textContent=`${other.length} sale${other.length===1?'':'s'}`;}
function applyFilters(){const q=els.search.value.trim().toLowerCase();const from=els.from.value?new Date(`${els.from.value}T00:00:00`):null;const to=els.to.value?new Date(`${els.to.value}T23:59:59.999`):null;filtered=transactions.filter(tx=>{if(els.type.value&&tx.type!==els.type.value)return false;if(els.provider.value&&tx.provider!==els.provider.value)return false;if(els.status.value&&tx.status!==els.status.value)return false;const when=txDate(tx);if(from&&when<from)return false;if(to&&when>to)return false;if(q){const hay=[tx.id,tx.type,tx.title,tx.description,tx.reference,tx.customerName,tx.customerEmail,tx.customerPhone,tx.provider,tx.providerPaymentId,tx.providerOrderId,paymentMethod(tx),JSON.stringify(tx.metadata||{})].join(' ').toLowerCase();if(!hay.includes(q))return false;}return true;});updateStats();render();renderCalendar();}
function render(){els.rows.innerHTML='';els.cards.innerHTML='';els.resultCount.textContent=filtered.length;els.empty.classList.toggle('hidden',filtered.length>0);for(const tx of filtered){const tr=document.createElement('tr');tr.className='clickable';tr.innerHTML=`<td>${esc(dt(tx.paidAt||tx.createdAt))}</td><td><strong>${esc(typeLabel(tx.type))}</strong><small>${esc(detailText(tx))}</small></td><td><strong>${esc(tx.customerName||'—')}</strong><small>${esc(tx.customerEmail||tx.customerPhone||'')}</small></td><td class="money">${esc(money(tx.amountCents,tx.currency||'USD'))}</td><td><span class="provider-badge ${esc(tx.provider||'')}">${esc(paymentMethod(tx))}</span></td><td><span class="status ${String(tx.status||'').toLowerCase()}">${esc(tx.status||'—')}</span></td>`;tr.addEventListener('click',()=>openDetail(tx));els.rows.appendChild(tr);const card=document.createElement('article');card.className='tx-card';card.innerHTML=`<div class="tx-top"><div><div class="tx-title">${esc(typeLabel(tx.type))}</div><div class="tx-sub">${esc(detailText(tx))}</div></div><div class="tx-money">${esc(money(tx.amountCents,tx.currency||'USD'))}</div></div><div class="tx-meta"><span>${esc(tx.customerName||'Unknown customer')}</span><span>•</span><span>${esc(paymentMethod(tx))}</span><span>•</span><span>${esc(dt(tx.paidAt||tx.createdAt))}</span></div>`;card.addEventListener('click',()=>openDetail(tx));els.cards.appendChild(card);}}
function setView(view){currentView=view==='calendar'?'calendar':'list';localStorage.setItem('payhub_view',currentView);const cal=currentView==='calendar';els.listView.classList.toggle('hidden',cal);els.calendarView.classList.toggle('hidden',!cal);els.listViewBtn.classList.toggle('active',!cal);els.calendarViewBtn.classList.toggle('active',cal);els.viewHeading.textContent=cal?'Calendar filters':'Transactions';if(cal)renderCalendar();}
function renderCalendar(){if(!els.calendarGrid)return;const year=calendarCursor.getFullYear();const month=calendarCursor.getMonth();const monthStart=new Date(year,month,1);const gridStart=new Date(year,month,1-monthStart.getDay());const monthName=monthStart.toLocaleDateString([], {month:'long',year:'numeric'});els.calendarMonth.textContent=monthName;const monthTx=filtered.filter(t=>{const d=txDate(t);return d.getFullYear()===year&&d.getMonth()===month;});const monthRevenue=monthTx.reduce((s,t)=>s+(Number(t.amountCents)||0),0);els.calendarSummary.textContent=`${money(monthRevenue)} · ${monthTx.length} payment${monthTx.length===1?'':'s'}`;els.calendarGrid.innerHTML='';const todayKey=localDateKey(new Date());for(let i=0;i<42;i++){const day=new Date(gridStart);day.setDate(gridStart.getDate()+i);const key=localDateKey(day);const dayTx=filtered.filter(t=>localDateKey(txDate(t))===key);const total=dayTx.reduce((s,t)=>s+(Number(t.amountCents)||0),0);const btn=document.createElement('button');btn.type='button';btn.className='calendar-day';if(day.getMonth()!==month)btn.classList.add('outside');if(key===todayKey)btn.classList.add('today');if(dayTx.length)btn.classList.add('has-sales');const types=[...new Set(dayTx.map(t=>t.type))];btn.innerHTML=`<span class="day-number">${day.getDate()}</span>${dayTx.length?`<span class="day-types">${types.map(t=>`<i class="day-dot ${esc(t)}" title="${esc(typeLabel(t))}"></i>`).join('')}</span><span class="day-total">${esc(money(total))}</span><span class="day-count">${dayTx.length} payment${dayTx.length===1?'':'s'}</span>`:''}`;if(dayTx.length)btn.addEventListener('click',()=>openCalendarDay(day,dayTx));els.calendarGrid.appendChild(btn);}}
function openCalendarDay(day,dayTx){const total=dayTx.reduce((s,t)=>s+(Number(t.amountCents)||0),0);els.detailEyebrow.textContent='Daily payments';els.detailTitle.textContent=`${day.toLocaleDateString([], {weekday:'short',month:'short',day:'numeric'})} · ${money(total)}`;els.detailBody.innerHTML=`<div class="calendar-day-list">${dayTx.map(tx=>`<article class="tx-card" data-tx-id="${esc(tx.id)}"><div class="tx-top"><div><div class="tx-title">${esc(typeLabel(tx.type))}</div><div class="tx-sub">${esc(detailText(tx))}</div></div><div class="tx-money">${esc(money(tx.amountCents,tx.currency||'USD'))}</div></div><div class="tx-meta"><span>${esc(tx.customerName||'Unknown customer')}</span><span>•</span><span>${esc(paymentMethod(tx))}</span><span>•</span><span>${esc(dt(tx.paidAt||tx.createdAt))}</span></div></article>`).join('')}</div>`;els.detailBody.querySelectorAll('[data-tx-id]').forEach(card=>card.addEventListener('click',()=>{const tx=transactions.find(t=>t.id===card.dataset.txId);if(tx)openDetail(tx);}));if(!els.dialog.open)els.dialog.showModal();}
function item(label,value,wide=false,code=false){return `<div class="detail-item${wide?' wide':''}"><span>${esc(label)}</span>${code?`<code>${esc(value||'—')}</code>`:`<strong>${esc(value||'—')}</strong>`}</div>`;}
function openDetail(tx){els.detailEyebrow.textContent='Transaction details';els.detailTitle.textContent=`${typeLabel(tx.type)} · ${money(tx.amountCents,tx.currency||'USD')}`;const meta=tx.metadata&&Object.keys(tx.metadata).length?JSON.stringify(tx.metadata,null,2):'No extra metadata';els.detailBody.innerHTML=[item('Status',tx.status),item('Paid with',paymentMethod(tx)),item('Card / wallet detail',tx.paymentDetails?.cardBrand?(tx.paymentDetails.cardBrand+(tx.paymentDetails.last4?' •••• '+tx.paymentDetails.last4:'')):(tx.paymentDetails?.cashTag||tx.paymentDetails?.venmoUser||'—')),item('Processor',tx.provider||'—'),item('Fulfillment',tx.fulfillmentStatus||'—'),item('Customer',tx.customerName||'—'),item('Email',tx.customerEmail||'—'),item('Phone',tx.customerPhone||'—'),item('What it was for',detailText(tx)),item('Created',dt(tx.createdAt)),item('Paid',dt(tx.paidAt)),item('Intent ID',tx.id,true,true),item('Provider payment ID',tx.providerPaymentId||'—',true,true),item('Provider order ID',tx.providerOrderId||'—',true,true),item('Reference',tx.reference||'—',true,true),`<div class="detail-item wide"><span>Metadata / notes</span><pre class="detail-json">${esc(meta)}</pre></div>`].join('');if(!els.dialog.open)els.dialog.showModal();}
function exportCsv(){const cols=['paid_at','created_at','type','description','customer_name','customer_email','customer_phone','amount','currency','payment_method','payment_detail','provider','status','fulfillment_status','reference','intent_id','provider_payment_id','provider_order_id','metadata'];const quote=v=>`"${String(v??'').replaceAll('"','""')}"`;const lines=[cols.join(',')];for(const t of filtered){lines.push([t.paidAt,t.createdAt,typeLabel(t.type),detailText(t),t.customerName,t.customerEmail,t.customerPhone,(Number(t.amountCents||0)/100).toFixed(2),t.currency,paymentMethod(t),t.paymentDetails?.cardBrand?(t.paymentDetails.cardBrand+(t.paymentDetails.last4?' •••• '+t.paymentDetails.last4:'')):(t.paymentDetails?.cashTag||t.paymentDetails?.venmoUser||''),t.provider,t.status,t.fulfillmentStatus,t.reference,t.id,t.providerPaymentId,t.providerOrderId,JSON.stringify(t.metadata||{})].map(quote).join(','));}const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pay-hub-sales-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
els.loginForm.addEventListener('submit',async e=>{e.preventDefault();adminKey=els.adminKey.value.trim();els.loginError.textContent='';if(els.remember.checked)localStorage.setItem('payhub_admin_key',adminKey);else sessionStorage.setItem('payhub_admin_key',adminKey);await loadAll();});
els.logout.addEventListener('click',()=>lock());els.refresh.addEventListener('click',loadAll);els.export.addEventListener('click',exportCsv);[els.search,els.type,els.provider,els.status,els.from,els.to].forEach(el=>el.addEventListener(el===els.search?'input':'change',applyFilters));els.clear.addEventListener('click',()=>{[els.search,els.type,els.provider,els.status,els.from,els.to].forEach(el=>el.value='');applyFilters();clearQuickActive();});els.closeDialog.addEventListener('click',()=>els.dialog.close());els.dialog.addEventListener('click',e=>{if(e.target===els.dialog)els.dialog.close();});els.listViewBtn.addEventListener('click',()=>setView('list'));els.calendarViewBtn.addEventListener('click',()=>setView('calendar'));els.calendarPrev.addEventListener('click',()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()-1,1);renderCalendar();});els.calendarNext.addEventListener('click',()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+1,1);renderCalendar();});els.calendarToday.addEventListener('click',()=>{const now=new Date();calendarCursor=new Date(now.getFullYear(),now.getMonth(),1);renderCalendar();});

const quickStyle=document.createElement('style');
quickStyle.textContent=`.stat.quick-tab{cursor:pointer;transition:transform .15s ease,border-color .15s ease,box-shadow .15s ease}.stat.quick-tab:hover{transform:translateY(-2px);border-color:rgba(146,91,255,.55)}.stat.quick-tab:focus-visible{outline:3px solid rgba(146,91,255,.65);outline-offset:3px}.stat.quick-tab.quick-active{border-color:var(--purple);box-shadow:0 0 0 2px rgba(146,91,255,.2),var(--shadow)}.stat.quick-tab.quick-active.accent{border-color:var(--green);box-shadow:0 0 0 2px rgba(124,255,91,.18),var(--shadow)}`;
document.head.appendChild(quickStyle);
const quickCards={paid:$('#statRevenue')?.closest('.stat'),tip:$('#statTips')?.closest('.stat'),song_request:$('#statSongs')?.closest('.stat'),other:$('#statOther')?.closest('.stat')};
function clearQuickActive(){Object.values(quickCards).forEach(card=>card?.classList.remove('quick-active'));}
function showQuick(kind){clearQuickActive();quickCards[kind]?.classList.add('quick-active');els.search.value='';els.type.value='';els.provider.value='';els.status.value='PAID';els.from.value='';els.to.value='';if(kind==='tip'||kind==='song_request'){els.type.value=kind;applyFilters();}else if(kind==='paid'){applyFilters();}else{filtered=transactions.filter(tx=>tx.status==='PAID'&&!['tip','song_request'].includes(tx.type));updateStats();render();renderCalendar();}setView(currentView);}
Object.entries(quickCards).forEach(([kind,card])=>{if(!card)return;card.classList.add('quick-tab');card.setAttribute('role','button');card.setAttribute('tabindex','0');card.setAttribute('aria-label',kind==='paid'?'Show all paid sales':kind==='tip'?'Show tips only':kind==='song_request'?'Show song requests only':'Show other sales only');card.addEventListener('click',()=>showQuick(kind));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showQuick(kind);}});});
[els.search,els.type,els.provider,els.status,els.from,els.to].forEach(el=>el.addEventListener(el===els.search?'input':'change',clearQuickActive));

if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
if(adminKey){els.remember.checked=Boolean(localStorage.getItem('payhub_admin_key'));loadAll();}
setInterval(()=>{if(adminKey&&!document.hidden)loadAll();},60000);
