function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function parse(v,f={}){try{return JSON.parse(v)}catch{return f}}
function bearer(request,expected){if(!expected)return false;const h=request.headers.get('authorization')||'';return h.startsWith('Bearer ')&&h.slice(7)===expected}
function serialize(row){return {id:row.id,type:row.type,originApp:row.origin_app,status:row.status,fulfillmentStatus:row.fulfillment_status,amountCents:row.amount_cents,currency:row.currency,title:row.title,description:row.description,reference:row.reference,customerName:row.customer_name,customerEmail:row.customer_email,customerPhone:row.customer_phone,metadata:parse(row.metadata_json,{}),createdAt:row.created_at,paidAt:row.paid_at,provider:row.provider,providerPaymentId:row.provider_payment_id,providerOrderId:row.provider_order_id}}
export async function onRequestGet({request,env}){
  if(!bearer(request,env.ADMIN_API_KEY))return json({error:'Unauthorized.'},401);
  try{
    const url=new URL(request.url);const requestedLimit=Number(url.searchParams.get('limit')||200);const requestedOffset=Number(url.searchParams.get('offset')||0);const limit=Number.isFinite(requestedLimit)?Math.min(Math.max(Math.trunc(requestedLimit),1),500):200;const offset=Number.isFinite(requestedOffset)?Math.max(Math.trunc(requestedOffset),0):0;
    const [rows,countRow]=await Promise.all([env.PAYMENT_DB.prepare('SELECT * FROM payment_intents ORDER BY created_at DESC LIMIT ? OFFSET ?').bind(limit,offset).all(),env.PAYMENT_DB.prepare('SELECT COUNT(*) AS total FROM payment_intents').first()]);
    const transactions=(rows.results||[]).map(serialize);
    // Payment-method enrichment is best-effort. A malformed/legacy event must never block the manager.
    try{
      if(transactions.length){const ids=transactions.map(t=>t.id);const placeholders=ids.map(()=>'?').join(',');const events=await env.PAYMENT_DB.prepare(`SELECT intent_id,payload_json FROM payment_events WHERE intent_id IN (${placeholders}) ORDER BY created_at DESC`).bind(...ids).all();const by=new Map();for(const e of(events.results||[])){if(!by.has(e.intent_id))by.set(e.intent_id,[]);by.get(e.intent_id).push(e)}for(const tx of transactions){let method=tx.provider==='square'?'Square':tx.provider==='paypal'?'PayPal':(tx.provider||null);const details={};for(const e of(by.get(tx.id)||[])){const p=parse(e.payload_json,{});const payment=p?.payment||p?.data?.object?.payment||null;if(payment){const card=payment?.card_details?.card||{};const wallet=payment?.wallet_details||{};if(payment.source_type==='WALLET'&&wallet.brand==='CASH_APP'){method='Cash App Pay';if(wallet.cash_app_details?.buyer_cashtag)details.cashTag=wallet.cash_app_details.buyer_cashtag}else if(payment?.card_details?.wallet_type==='APPLE_PAY')method='Apple Pay';else if(payment.source_type==='CARD')method='Card';if(card.card_brand)details.cardBrand=card.card_brand;if(card.last_4)details.last4=card.last_4}const source=p?.payment_source||{};if(source.venmo){method='Venmo';if(source.venmo.user_name)details.venmoUser=source.venmo.user_name}else if(source.paypal)method='PayPal';else if(source.card){method='Card';if(source.card.brand)details.cardBrand=source.card.brand;if(source.card.last_digits)details.last4=source.card.last_digits}}tx.paymentMethod=method;tx.paymentDetails=details}}
    }catch(e){console.error('Manager payment-method enrichment skipped',e);for(const tx of transactions){tx.paymentMethod=tx.provider==='square'?'Square':tx.provider==='paypal'?'PayPal':(tx.provider||null);tx.paymentDetails={}}}
    return json({transactions,total:Number(countRow?.total||0),limit,offset});
  }catch(e){console.error('Manager transactions failed',e);return json({error:'Could not load transactions.',detail:String(e?.message||e)},500)}
}
